Bump to 0.4.0
powerhome/power_linting pull request #32
Opened 2022-05-31 18:11 UTC by garettarrowood

This release will contain 3 new cops

2022-05-31 19:03 UTC, benlangfeld requested changes
Holding just incase someone doesn't notice the date and merges today.

2022-05-31 19:03 UTC, benlangfeld commented on rubocop-cobra/CHANGELOG.md
> +## [0.4.0] - 2022-06-01
Why tomorrow?

2022-05-31 19:03 UTC, benlangfeld commented
Can someone from @powerhome/heroes-for-hire also backfill the changelog with the missing releases?

2022-06-01 13:45 UTC, xjunior approved these changes

2022-06-01 14:28 UTC, merged